version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: google_auth0
    ports:
      - '5438:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nest-network

  app:
    build: .
    container_name: nest-google-auth0
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: google_auth0
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nest-network

volumes:
  postgres-data:

networks:
  nest-network:
    driver: bridge
